# thanks to https://github.com/travis-ci/travis-ci/issues/5775
sudo: false

language: r
r:
  - oldrel
  - release
  - devel

cache: packages

install:
  - Rscript -e 'install.packages(c("devtools","roxygen2","testthat","dplyr","tidyr", "knitr", "rmarkdown", "ggplot2", "scales", "ggthemes", "GGally", "ggrepel", "maps", "mapproj", "forcats"));devtools::install_deps("pkg1");devtools::install_deps("pkg2")'
script:
  - Rscript -e 'devtools::check("pkg1")'
  - Rscript -e 'devtools::check("pkg2")'

notifications:
  email:
    on_success: change
    on_failure: change